name 'vchepkov-puppet-bootstrap'
version '0.0.1'
source 'https://github.com/vchepkov/puppet-bootstrap'
author 'vchepkov'
license 'Apache License, Version 2.0'
summary 'Bootstrap puppet environment with r10k'
description 'Module to bootstrap puppet configuration to support multiple environments with r10k' 
project_page 'https://github.com/puppet-bootstrap'

dependency 'puppetlabs/stdlib',  '>= 3.2.0'
dependency 'zack/r10k',          '>= 1.0.2'
